FROM fedora

MAINTAINER Fredy Muñoz <fredy@munoz.im>

RUN dnf -y install \
      ruby \
      sqlite \
      rubygem-rails \
      rubygem-sqlite3 \
      rubygem-coffee-rails \
      rubygem-sass-rails \
      rubygem-uglifier \
      rubygem-jquery-rails \
      rubygem-turbolinks \
      rubygem-jbuilder \
      rubygem-therubyracer \
      rubygem-sdoc \
      rubygem-spring \
      rubygem-byebug \
      rubygem-web-console

CMD /bin/bash


# References
# ----------
#
# https://developer.fedoraproject.org/tech/languages/ruby/ror-installation.html
# https://fedoraproject.org/wiki/Changes/Ruby_on_Rails_4.2
# https://fedoraproject.org/wiki/Ruby_SIG
